language: go
sudo: false

go:
  - 1.8.x

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 84607742b10f492430762d038e954236bbaf23f7 && go install && cd -
  - make deps

script:
  - make test

after_success:
  - make test-all-cov
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make build-all
  - make dist

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  skip_cleanup: true
  file_glob: true
  file: 'dist/*.{tar.gz, zip}'
  on:
    tags: true