language: go
sudo: false

go:
  - 1.8.x

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 84607742b10f492430762d038e954236bbaf23f7 && go install && cd -
  - make deps

script:
  - make testallcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
