language: go
sudo: false

go:
  - "1.11"

install: true

script:
  - env GO111MODULE=on go test ./...

after_success:
  - env GO111MODULE=on go test -coverprofile=coverage.txt -covermode=atomic ./...
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - env GO111MODULE=on make build-all
  - make dist

deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  skip_cleanup: true
  file_glob: true
  file: 'dist/*.{tar.gz, zip}'
  on:
    tags: true